const ShipmozoLabelSettings = require('../models/ShipmozoLabelSettings');
const logger = require('../utils/logger');

const VALID_STOREFRONTS = new Set(['ecomm', 'wholesale']);

function normalizeStorefront(value) {
  const s = String(value || 'ecomm').toLowerCase().trim();
  return VALID_STOREFRONTS.has(s) ? s : 'ecomm';
}

function asBool(v, fallback) {
  if (v === true || v === false) return v;
  if (v === 'true' || v === 1 || v === '1') return true;
  if (v === 'false' || v === 0 || v === '0') return false;
  return fallback;
}

function asInt(v, fallback, min, max) {
  const n = Number.parseInt(String(v ?? ''), 10);
  if (!Number.isFinite(n)) return fallback;
  return Math.min(max, Math.max(min, n));
}

function asStr(v, maxLen) {
  return String(v == null ? '' : v).trim().slice(0, maxLen);
}

function defaultSettings() {
  return {
    labelSize: '4x6',
    support: {
      showCustomerSupport: true,
      mobile: '',
      email: String(process.env.STORE_EMAIL || 'support.offerwalebaba@gmail.com').trim()
    },
    delivery: {
      showPaymentMode: true,
      showCustomerAddress: true,
      showCustomerPhone: false,
      showOrderBarcode: true,
      showAwbBarcode: true,
      showRoutingCode: true,
      showRtoRoutingCode: true,
      showDimension: true,
      showWeight: true
    },
    pickup: {
      showPickupName: true,
      showPickupAddress: true,
      showPickupPhone: false,
      showRtoName: true,
      showRtoAddress: true,
      showGstin: false,
      gstin: String(process.env.STORE_GSTIN || '').trim(),
      sellerName: ''
    },
    products: {
      showItem: true,
      showSku: true,
      showQty: true,
      showPrice: true,
      showTotal: true,
      showHsn: false,
      showTaxableAmount: false,
      showDiscount: false,
      showPlatformFee: false,
      showShippingCharges: true,
      showCollectableAmount: true,
      showTotalQuantity: true,
      showAllItems: false,
      trimSkuUpto: 10,
      trimProductNameUpto: 10,
      maxLineItems: 10
    },
    misc: {
      showNotes: true,
      notes:
        "All disputes are subject to Haryana Jurisdiction only. Goods once sold will only be taken back or exchanged as per store's exchange and return policy.",
      showInvoiceNumber: true,
      showInvoiceDate: true,
      showOrderDate: true,
      showOrderTotal: true,
      showEwayBill: true,
      showPoweredBy: true,
      showAutoGeneratedDisclaimer: true,
      showBorderToPageEnd: true
    }
  };
}

function mergeSection(defaults, incoming, spec) {
  const src = incoming && typeof incoming === 'object' ? incoming : {};
  const out = { ...defaults };
  for (const [key, kind] of Object.entries(spec)) {
    if (!Object.prototype.hasOwnProperty.call(src, key)) continue;
    if (kind === 'bool') out[key] = asBool(src[key], defaults[key]);
    else if (kind.type === 'int') out[key] = asInt(src[key], defaults[key], kind.min, kind.max);
    else if (kind.type === 'str') out[key] = asStr(src[key], kind.max);
  }
  return out;
}

/**
 * Sanitize a partial/full settings payload. Unknown keys dropped. Weight/dims stay on.
 */
function sanitizeSettings(incoming) {
  const d = defaultSettings();
  const src = incoming && typeof incoming === 'object' ? incoming : {};
  try {
    return {
      labelSize: '4x6',
      support: mergeSection(d.support, src.support, {
        showCustomerSupport: 'bool',
        mobile: { type: 'str', max: 20 },
        email: { type: 'str', max: 120 }
      }),
      delivery: {
        ...mergeSection(d.delivery, src.delivery, {
          showPaymentMode: 'bool',
          showCustomerAddress: 'bool',
          showCustomerPhone: 'bool',
          showOrderBarcode: 'bool',
          showAwbBarcode: 'bool',
          showRoutingCode: 'bool',
          showRtoRoutingCode: 'bool',
          showDimension: 'bool',
          showWeight: 'bool'
        }),
        showDimension: true,
        showWeight: true
      },
      pickup: mergeSection(d.pickup, src.pickup, {
        showPickupName: 'bool',
        showPickupAddress: 'bool',
        showPickupPhone: 'bool',
        showRtoName: 'bool',
        showRtoAddress: 'bool',
        showGstin: 'bool',
        gstin: { type: 'str', max: 20 },
        sellerName: { type: 'str', max: 80 }
      }),
      products: mergeSection(d.products, src.products, {
        showItem: 'bool',
        showSku: 'bool',
        showQty: 'bool',
        showPrice: 'bool',
        showTotal: 'bool',
        showHsn: 'bool',
        showTaxableAmount: 'bool',
        showDiscount: 'bool',
        showPlatformFee: 'bool',
        showShippingCharges: 'bool',
        showCollectableAmount: 'bool',
        showTotalQuantity: 'bool',
        showAllItems: 'bool',
        trimSkuUpto: { type: 'int', min: 4, max: 40 },
        trimProductNameUpto: { type: 'int', min: 4, max: 40 },
        maxLineItems: { type: 'int', min: 1, max: 30 }
      }),
      misc: mergeSection(d.misc, src.misc, {
        showNotes: 'bool',
        notes: { type: 'str', max: 500 },
        showInvoiceNumber: 'bool',
        showInvoiceDate: 'bool',
        showOrderDate: 'bool',
        showOrderTotal: 'bool',
        showEwayBill: 'bool',
        showPoweredBy: 'bool',
        showAutoGeneratedDisclaimer: 'bool',
        showBorderToPageEnd: 'bool'
      })
    };
  } catch (err) {
    logger.error('sanitizeSettings failed', { message: err?.message });
    return d;
  }
}

async function getOrCreateDoc(storefront) {
  const sf = normalizeStorefront(storefront);
  let doc = await ShipmozoLabelSettings.findOne({ storefront: sf });
  if (!doc) {
    doc = await ShipmozoLabelSettings.create({
      storefront: sf,
      settings: defaultSettings()
    });
  }
  return doc;
}

async function getPublicSettings(storefront) {
  const sf = normalizeStorefront(storefront);
  const doc = await getOrCreateDoc(sf);
  const settings = sanitizeSettings(doc.settings);
  return {
    storefront: sf,
    labelSize: '4x6',
    settings,
    updatedAt: doc.updatedAt || null
  };
}

async function saveSettings(storefront, patch, updatedBy) {
  const sf = normalizeStorefront(storefront);
  const settings = sanitizeSettings(patch);
  const doc = await ShipmozoLabelSettings.findOneAndUpdate(
    { storefront: sf },
    {
      $set: {
        settings,
        updatedBy: updatedBy || null
      }
    },
    { upsert: true, new: true, setDefaultsOnInsert: true }
  );
  return {
    storefront: sf,
    labelSize: '4x6',
    settings: sanitizeSettings(doc.settings),
    updatedAt: doc.updatedAt || null
  };
}

module.exports = {
  normalizeStorefront,
  defaultSettings,
  sanitizeSettings,
  getPublicSettings,
  saveSettings
};
