/**
 * OTP Delivery Configuration
 * ---------------------------
 * Single source of truth for "where does the OTP go?".
 *
 * Reads the env variable OTP_DELIVERY_MODE and routes OTP delivery to either
 * the SMS provider (existing `sms.config.js`), the email provider, or both.
 *
 * Modes:
 *   - "sms"   (default) — Send OTP via SMS only.
 *   - "email"           — Send OTP via Email only.
 *   - "both"            — Send OTP via both channels in parallel.
 *
 * Design goals:
 *   - Backward compatible: if env is missing/empty/invalid → falls back to "sms".
 *   - Robust: in "both" mode, partial success (one channel works) is still
 *     considered a success — the failing channel's error is reported but does
 *     not block the OTP flow.
 *   - Explicit override: callers (e.g. password-reset flow that picks channel
 *     based on the user-supplied identifier) can pass `forceChannel` to bypass
 *     the env-based mode.
 *   - Validates required identifier per channel — clean 400-ish error if
 *     `email` mode is configured but caller didn't supply an email.
 */

const smsProvider = require('./sms.config');
const emailProvider = require('../providers/email-otp.provider');

const OTP_DELIVERY_MODES = Object.freeze({
  SMS: 'sms',
  EMAIL: 'email',
  BOTH: 'both'
});

const VALID_MODES = new Set(Object.values(OTP_DELIVERY_MODES));

const DEFAULT_OTP_EXPIRY_MINUTES = 5;
const MAX_OTP_EXPIRY_MINUTES = 60;

/**
 * Resolve the OTP expiry window (in minutes) from env.
 *
 * Env: OTP_EXPIRY_MINUTES   (positive integer, 1..60). Anything invalid
 *      → falls back to DEFAULT_OTP_EXPIRY_MINUTES.
 *
 * Used uniformly by every OTP flow (registration, password reset,
 * wholesaler activation, contact change, email template body) so the entire
 * platform stays consistent.
 */
const getOtpExpiryMinutes = () => {
  const raw = Number(process.env.OTP_EXPIRY_MINUTES);
  if (Number.isFinite(raw) && raw > 0 && raw <= MAX_OTP_EXPIRY_MINUTES) {
    return Math.floor(raw);
  }
  return DEFAULT_OTP_EXPIRY_MINUTES;
};

const getOtpExpiryMs = () => getOtpExpiryMinutes() * 60 * 1000;

/**
 * Resolve the configured delivery mode from env.
 * Always returns one of OTP_DELIVERY_MODES values.
 */
const getDeliveryMode = () => {
  const raw = String(process.env.OTP_DELIVERY_MODE || '').trim().toLowerCase();
  if (VALID_MODES.has(raw)) return raw;
  // Soft-default to SMS — preserves pre-existing behaviour.
  return OTP_DELIVERY_MODES.SMS;
};

/**
 * Internal: send via SMS, isolated so caller can swallow/log errors.
 */
const trySendSms = async (phone, otp) => {
  if (!phone) {
    const err = new Error('Phone number required for SMS OTP delivery');
    err.code = 'OTP_SMS_RECIPIENT_MISSING';
    throw err;
  }
  await smsProvider.sendSMS(phone, otp);
  return { channel: OTP_DELIVERY_MODES.SMS, target: phone };
};

/**
 * Internal: send via Email, isolated so caller can swallow/log errors.
 */
const trySendEmail = async (email, otp, purpose) => {
  if (!email) {
    const err = new Error('Email address required for Email OTP delivery');
    err.code = 'OTP_EMAIL_RECIPIENT_MISSING';
    throw err;
  }
  await emailProvider.sendEmailOTP({
    to: email,
    otp,
    purpose,
    minutes: getOtpExpiryMinutes()
  });
  return { channel: OTP_DELIVERY_MODES.EMAIL, target: email };
};

/**
 * Deliver an OTP across the configured channels.
 *
 * @param {Object} params
 * @param {string} [params.phone]       Recipient phone (10-digit). Required if mode includes SMS.
 * @param {string} [params.email]       Recipient email. Required if mode includes Email.
 * @param {string} params.otp           The OTP code to send (already generated by caller).
 * @param {string} [params.purpose]     Used by email template selection — e.g. "registration".
 * @param {("sms"|"email"|"both")} [params.forceChannel]
 *        Override env-driven mode. Useful for flows like password-reset where
 *        the user-supplied identifier dictates the channel.
 *
 * @returns {Promise<{
 *   deliveryMode: string,
 *   deliveredVia: string[],
 *   targets: { sms?: string, email?: string },
 *   errors: { sms?: string, email?: string }
 * }>}
 *
 * @throws If NONE of the attempted channels succeed.
 */
const deliverOTP = async ({ phone, email, otp, purpose = 'generic', forceChannel } = {}) => {
  if (!otp) {
    const err = new Error('OTP value is required for delivery');
    err.code = 'OTP_PAYLOAD_MISSING';
    throw err;
  }

  const mode = forceChannel && VALID_MODES.has(String(forceChannel).toLowerCase())
    ? String(forceChannel).toLowerCase()
    : getDeliveryMode();

  const wantsSms = mode === OTP_DELIVERY_MODES.SMS || mode === OTP_DELIVERY_MODES.BOTH;
  const wantsEmail = mode === OTP_DELIVERY_MODES.EMAIL || mode === OTP_DELIVERY_MODES.BOTH;

  const deliveredVia = [];
  const targets = {};
  const errors = {};

  // Fan-out — parallel sends so neither channel blocks the other.
  const ops = [];

  if (wantsSms) {
    ops.push(
      trySendSms(phone, otp)
        .then((r) => {
          deliveredVia.push(OTP_DELIVERY_MODES.SMS);
          targets.sms = r.target;
        })
        .catch((e) => {
          errors.sms = e?.message || 'SMS delivery failed';
          console.error('[otp-delivery] SMS send failed:', errors.sms);
        })
    );
  }

  if (wantsEmail) {
    ops.push(
      trySendEmail(email, otp, purpose)
        .then((r) => {
          deliveredVia.push(OTP_DELIVERY_MODES.EMAIL);
          targets.email = r.target;
        })
        .catch((e) => {
          errors.email = e?.message || 'Email delivery failed';
          console.error('[otp-delivery] Email send failed:', errors.email);
        })
    );
  }

  await Promise.all(ops);

  if (deliveredVia.length === 0) {
    // Both attempted channels failed → hard error.
    const err = new Error('OTP delivery failed on all configured channels');
    err.code = 'OTP_DELIVERY_FAILED';
    err.details = errors;
    throw err;
  }

  return {
    deliveryMode: mode,
    deliveredVia,
    targets,
    errors
  };
};

/**
 * Lightweight predicate so callers (e.g. controllers) can short-circuit and
 * validate that the required identifier is present BEFORE generating an OTP
 * and persisting state to the DB.
 */
const validateRecipientsForMode = ({ phone, email, forceChannel } = {}) => {
  const mode = forceChannel && VALID_MODES.has(String(forceChannel).toLowerCase())
    ? String(forceChannel).toLowerCase()
    : getDeliveryMode();

  if (mode === OTP_DELIVERY_MODES.SMS && !phone) {
    return { ok: false, mode, missing: 'phone' };
  }
  if (mode === OTP_DELIVERY_MODES.EMAIL && !email) {
    return { ok: false, mode, missing: 'email' };
  }
  if (mode === OTP_DELIVERY_MODES.BOTH && !phone && !email) {
    return { ok: false, mode, missing: 'phone_or_email' };
  }
  return { ok: true, mode };
};

module.exports = {
  OTP_DELIVERY_MODES,
  getDeliveryMode,
  deliverOTP,
  validateRecipientsForMode,
  getOtpExpiryMinutes,
  getOtpExpiryMs
};
